In [1]:
import numpy as np
import torch
import matplotlib as mp

# Problem 1

In [33]:
A = np.array([[1,2,5,1], [3,4,1,0]])
A_mean = A.mean(axis=1)
print(A_mean)

[2.25 2.  ]


# Problem 7

In [ ]:
# a
table1 = np.array([[0,1,0,1,2],
                   [1,3,2,1,0],
                   [0,0,0,1,3]])

table2 = np.array([[157,167,130,145,170],
                    [250,260,263,273,290],
                    [301,120,30,100,502]])

table3 = np.array([[1,1,1,1,1],
                   [0,0,0,0,0],
                   [0,0,0,0,0]])


array([[0, 1, 0, 1, 2],
       [1, 3, 2, 1, 0],
       [0, 0, 0, 1, 3]])

In [8]:
# b


In [ ]:
# c
Y = np.stack([table1, table2, table3], axis=2)
Y

array([[[  0, 157,   1],
        [  1, 167,   1],
        [  0, 130,   1],
        [  1, 145,   1],
        [  2, 170,   1]],

       [[  1, 250,   0],
        [  3, 260,   0],
        [  2, 263,   0],
        [  1, 273,   0],
        [  0, 290,   0]],

       [[  0, 301,   0],
        [  0, 120,   0],
        [  0,  30,   0],
        [  1, 100,   0],
        [  3, 502,   0]]])

In [ ]:
# d

Y2 = 

In [ ]:
# e
task_e = np.transpose([Y], )

In [ ]:
# f

Y2 = np.stack([table1, table2, table3], axis=1)
Y2

array([[[  0,   1,   0,   1,   2],
        [157, 167, 130, 145, 170],
        [  1,   1,   1,   1,   1]],

       [[  1,   3,   2,   1,   0],
        [250, 260, 263, 273, 290],
        [  0,   0,   0,   0,   0]],

       [[  0,   0,   0,   1,   3],
        [301, 120,  30, 100, 502],
        [  0,   0,   0,   0,   0]]])

# Problem 8

In [16]:
data = np.loadtxt("HW_1_Problem_8.csv", delimiter=",", skiprows=1)
data.shape

(50, 6)

In [38]:
idx = data[:,0].argsort()
data = data[idx]

In [41]:
for i in range(10):
    idx = data[(i*5):((i+1)*5), 1].argsort() + i*5
    data[(i*5):((i+1)*5)] = data[idx]

In [42]:
data

array([[  1.,   1., 330., 164.,  92., 105.],
       [  1.,   2., 340., 170.,  99., 107.],
       [  1.,   3., 350., 176., 106., 109.],
       [  1.,   4., 360., 182., 113., 111.],
       [  1.,   5., 370., 188., 120., 113.],
       [  2.,   1., 350., 172.,  97., 108.],
       [  2.,   2., 360., 178., 104., 110.],
       [  2.,   3., 370., 184., 111., 112.],
       [  2.,   4., 380., 190., 118., 114.],
       [  2.,   5., 390., 196., 125., 116.],
       [  3.,   1., 370., 180., 102., 111.],
       [  3.,   2., 380., 186., 109., 113.],
       [  3.,   3., 390., 192., 116., 115.],
       [  3.,   4., 400., 198., 123., 117.],
       [  3.,   5., 410., 204., 130., 119.],
       [  4.,   1., 390., 188., 107., 114.],
       [  4.,   2., 400., 194., 114., 116.],
       [  4.,   3., 410., 200., 121., 118.],
       [  4.,   4., 420., 206., 128., 120.],
       [  4.,   5., 430., 212., 135., 122.],
       [  5.,   1., 410., 196., 112., 117.],
       [  5.,   2., 420., 202., 119., 119.],
       [  

In [ ]:
# sort 연습 부분

# 파괴동작 => X.sort()
# 비파괴동작: => np.sort(X)
# np.argsort => 인덱스 번호!! 완전 다른 건디...

In [31]:
arr = np.array([
    [1,10,3],
    [2,5,6],
    [3,8,1],
    [3,8,2]
])

# 방법1
arr[[1,2,0]]

# 방법2
idx = arr[:,1].argsort()
arr[idx]

array([[ 2,  5,  6],
       [ 3,  8,  1],
       [ 3,  8,  2],
       [ 1, 10,  3]])

In [ ]:
# problem 8 (2)

X = np.ones([10,5,4])
for i in range(10):
    for j in range(5):
        # 어느 행이 id은 i, year는 j냐?
        X[i,j,:] = data[(i,j), 2:]

In [ ]:
Net = np.ones([10,5])
Wealth = np.ones([10,5])

for i in range(10):
    for j in range(5):
        Net[i,j] = X[i,j,0] - X[i,j,1] + X[i,j,2]
        Wealth[i,j] = X[i,j,2] + X[i,j,3]

Y = np.stack([Net, Wealth], axis = 2)