# HW 1
## 학과: 경영학부
## 학번: 1985084
## 이름: 임수지

## 1. Basic Operations

# Problem 1

## Explanation:

- `axis=1` → 평균을 행(row) 단위로 구함.  
  - 예: 첫 번째 행 [1,2,5,1]의 평균은 2.25, 두 번째 행 [3,4,1,0]의 평균은 2.0.
- `keepdims=True` → `(n_rows, 1)` 형태로 결과를 유지해서 broadcasting이 가능하게 만듦.
- `matrix - row_means` → 각 행의 모든 원소에서 그 행의 평균을 빼는 연산이 한 번에 수행됨.
- 따라서 출력은 문제에서 요구한 것처럼 각 행에서 평균이 빠진 결과가 나온다.

In [38]:

import numpy as np

def subtract_row_means(matrix: np.ndarray) -> np.ndarray:
    # row-wise mean (shape: (n_rows, 1))
    row_means = matrix.mean(axis=1, keepdims=True)
    
    # broadcasting to subtract each row's mean
    return matrix - row_means


# Sample Input
A = np.array([[1,2,5,1], [3,4,1,0]])

# Apply function
result = subtract_row_means(A)
print(result)

[[-1.25 -0.25  2.75 -1.25]
 [ 1.    2.   -1.   -2.  ]]


# Problem 2

## Explanation:
- `axis=0` → 평균을 열(column) 단위로 구함.  
  - 각 열의 평균: [ (1+3)/2 = 2, (2+4)/2 = 3, (5+1)/2 = 3, (1+0)/2 = 0.5 ]  
- `keepdims=True` → `(1, n_cols)` 형태로 유지하여 broadcasting 가능.  
- `matrix - col_means` → 각 열에서 해당 열의 평균을 뺌.

In [39]:
import numpy as np

def subtract_col_means(matrix: np.ndarray) -> np.ndarray:
    # column-wise mean (shape: (1, n_cols))
    col_means = matrix.mean(axis=0, keepdims=True)
    
    # broadcasting to subtract each column's mean
    return matrix - col_means


# Sample Input
A = np.array([[1,2,5,1], [3,4,1,0]])

# Apply function
result = subtract_col_means(A)
print(result)


[[-1.  -1.   2.   0.5]
 [ 1.   1.  -2.  -0.5]]


# Problem 3 https://youtu.be/l6r003mzwH0?si=zyMK19aSxTl6xOqg 영상 0:00~0:30

## Explanation:
- `np.concatenate((A, B), axis=1)` → 두 배열을 **열(column) 방향으로** 이어 붙임.  
- `axis=0`이면 위아래로 붙고, `axis=1`이면 좌우로 붙는다.  
- A의 shape = (2, 2), B의 shape = (2, 1).  
- 따라서 결과 shape = (2, 3). 

In [40]:

import numpy as np

def concatenate_arrays(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    return np.concatenate((A, B), axis=1)


# Sample Input
A = np.array([[4.5, 3.5],
              [5.1, 2.3]])

B = np.array([[1],
              [2]])

# Apply function
result = concatenate_arrays(A, B)
print(result)


[[4.5 3.5 1. ]
 [5.1 2.3 2. ]]


# Problem 4

## Explanation:
- `np.concatenate((A, B), axis=0)` → 두 배열을 **행(row) 방향으로** 이어 붙임.  
- A의 shape = (2, 2), B의 shape = (3, 2).  
- 따라서 결과 shape = (5, 2).

In [41]:

import numpy as np

def concatenate_rowwise(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    return np.concatenate((A, B), axis=0)


# Sample Input
A = np.array([[4.5, 3.5],
              [5.1, 2.3]])

B = np.array([[4, 3],
              [5, 2],
              [1, 1]])

# Apply function
result = concatenate_rowwise(A, B)
print(result)


[[4.5 3.5]
 [5.1 2.3]
 [4.  3. ]
 [5.  2. ]
 [1.  1. ]]


# Problem 5 https://youtu.be/l6r003mzwH0?si=zyMK19aSxTl6xOqg 영상 0:31~1:07

## Explanation:
- `np.zeros((rows, cols), dtype=int)` → 모든 원소가 0인 행렬 생성.
- `mat[0, :] = 1` → 첫 번째 행을 모두 1로 설정.
- `mat[-1, :] = 1` → 마지막 행을 모두 1로 설정.
- `mat[:, 0] = 1` → 첫 번째 열을 모두 1로 설정.
- `mat[:, -1] = 1` → 마지막 열을 모두 1로 설정.
- 그 결과, **테두리는 1 / 내부는 0**인 행렬이 완성된다.

In [42]:

import numpy as np

def boundary_matrix(rows: int, cols: int) -> np.ndarray:
    # Initialize all zeros
    mat = np.zeros((rows, cols), dtype=int)
    
    # Fill boundary with 1
    mat[0, :] = 1         # top row
    mat[-1, :] = 1        # bottom row
    mat[:, 0] = 1         # first column
    mat[:, -1] = 1        # last column
    
    return mat


# Sample Input
result = boundary_matrix(10, 10)
print(result)


[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


# Problem 6

## Explanation:
- Moving average = 평균을 일정 구간(window)마다 계산한 것.  
- 예: \(k=3\), 첫 세 값 (3+5+7)/3 = 5.0, 그다음 (5+7+2)/3 = 4.67, … 이런 식으로 진행.  
- 코드에서 `np.convolve`는 **슬라이딩 윈도우 합**을 계산하는 빠른 방법.  
  - `np.ones(k)/k` → 길이 k인 윈도우를 만들어 평균 연산을 수행.  
  - `mode='valid'` → 윈도우가 완전히 들어맞는 부분만 결과로 반환 → 길이는 \(n-k+1\).  
- 따라서 테스트 결과는 길이가 \(13-3+1 = 11\)인 배열이 출력된다.

In [43]:

import numpy as np

def moving_average(arr, k: int) -> np.ndarray:
    arr = np.array(arr, dtype=float)
    n = len(arr)
    
    if k <= 0 or k > n:
        raise ValueError("Window size k must be > 0 and <= length of array")
    
    # Use convolution for efficient computation
    window = np.ones(k) / k
    return np.convolve(arr, window, mode='valid')


# Test
arr = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k = 3
result = moving_average(arr, k)
print(result)


[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]


# Problem 7 https://youtu.be/l6r003mzwH0?si=zyMK19aSxTl6xOqg 영상 1:08~2:47

## Explanation:
1. `N`, `Salary`, `Sports` 배열을 각각 [3,5] 크기로 만든다.  
2. 세 배열을 합쳐 [3,5,3] 형태의 `Y` 배열을 만든다. (사고 횟수, 급여, 스포츠카 정보 포함)  
3. (2)를 `N`, `Salary`, `Sports`를 이용해 다시 푼다.  
4. [3,3,5] 형태의 `Y2` 배열을 만든다.  
5. `np.transpose` 또는 `np.swapaxes`를 이용해 `Y`를 `Y2`로 변환한다.  
6. (4)를 `N`, `Salary`, `Sports`를 직접 이용해 다시 푼다.  

In [44]:
import numpy as np

# (a) Explicit arrays
N = np.array([[0, 1, 0, 1, 2],
              [1, 3, 2, 1, 0],
              [0, 0, 0, 1, 3]])

Salary = np.array([[157, 167, 130, 145, 170],
                   [250, 260, 263, 273, 290],
                   [301, 120,  30, 100, 502]])

Sports = np.array([[1, 1, 1, 1, 1],
                   [0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0]])

print("N:\n", N)
print("Salary:\n", Salary)
print("Sports:\n", Sports)


N:
 [[0 1 0 1 2]
 [1 3 2 1 0]
 [0 0 0 1 3]]
Salary:
 [[157 167 130 145 170]
 [250 260 263 273 290]
 [301 120  30 100 502]]
Sports:
 [[1 1 1 1 1]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [45]:
# (b) Explicit definition of Y [3,5,3]
Y = np.array([
    [[0, 157, 1],
     [1, 167, 1],
     [0, 130, 1],
     [1, 145, 1],
     [2, 170, 1]],
    
    [[1, 250, 0],
     [3, 260, 0],
     [2, 263, 0],
     [1, 273, 0],
     [0, 290, 0]],
    
    [[0, 301, 0],
     [0, 120, 0],
     [0,  30, 0],
     [1, 100, 0],
     [3, 502, 0]]
])
print("Y shape:", Y.shape)


Y shape: (3, 5, 3)


In [46]:
# (c) Build Y from N, Salary, Sports
Y_alt = np.stack((N, Salary, Sports), axis=2)
print("Y_alt shape:", Y_alt.shape)


Y_alt shape: (3, 5, 3)


In [47]:
# (d) Explicit definition of Y2 [3,3,5]
Y2 = np.array([
    [[0, 1, 0, 1, 2],
     [157, 167, 130, 145, 170],
     [1, 1, 1, 1, 1]],
    
    [[1, 3, 2, 1, 0],
     [250, 260, 263, 273, 290],
     [0, 0, 0, 0, 0]],
    
    [[0, 0, 0, 1, 3],
     [301, 120,  30, 100, 502],
     [0, 0, 0, 0, 0]]
])
print("Y2 shape:", Y2.shape)


Y2 shape: (3, 3, 5)


In [48]:
# (e) Convert Y -> Y2 via transpose
Y2_from_Y = np.transpose(Y, (0, 2, 1))   # swap axes: (3,5,3) -> (3,3,5)
print("Y2_from_Y shape:", Y2_from_Y.shape)


Y2_from_Y shape: (3, 3, 5)


In [49]:
# (f) Build Y2 directly from N, Salary, Sports
Y2_alt = np.stack((N, Salary, Sports), axis=1)
print("Y2_alt shape:", Y2_alt.shape)


Y2_alt shape: (3, 3, 5)


# Problem 8 https://youtu.be/l6r003mzwH0?si=zyMK19aSxTl6xOqg 영상 2:48~5:36

## Explanation:
- **(1)** `argsort()`로 ID, Year 기준 정렬 → `reshape()` 없이 인덱싱으로 `(10,5,4)` 배열 **X** 생성.  
- **(2)** `for` 반복문으로 `Net`과 `Wealth`를 계산 → `np.zeros()`로 배열 초기화 후 값 채움.  
- **(3)** `np.zeros()`로 `(50,4)` 배열 초기화 → 반복문에서 ID, Year, Net, Wealth 대입 → 필요 시 `np.savetxt()`로 CSV 저장.  
- **(4)** `np.array()`로 가중치 행렬 **W** 정의 → `@` (행렬 곱 연산자) 또는 `np.matmul()`로 `(10,5,2)` 배열 **Y** 계산.  


In [50]:
import numpy as np

data = np.loadtxt("hw_1_problem_8.csv", delimiter=",", skiprows=1)
data.shape


(50, 6)

In [51]:
# (1)
import numpy as np

# data: shape (50, 6), columns = [ID, Year, Income, Loss, Stock, House]

# (a) ID 기준 정렬
idx = data[:,0].argsort()   # ID 열 기준 정렬 인덱스
data = data[idx]

# (b) 각 ID 블록마다 Year 기준 정렬
for i in range(10):   # ID가 10개니까
    idx = data[i*5:(i+1)*5, 1].argsort() + i*5
    data[i*5:(i+1)*5] = data[idx]

# (c) X 만들기 (10, 5, 4)
X = np.zeros((10,5,4))
for i in range(10):
    for j in range(5):
        # ID=i, Year=j에 해당하는 row 선택
        X[i,j,:] = data[i*5+j, 2:]   # Income, Loss, Stock, House만

print("X shape:", X.shape)  # (10, 5, 4)
print("X[0,0,:] =", X[0,0,:])  # 첫 번째 ID, 첫 번째 Year의 값


X shape: (10, 5, 4)
X[0,0,:] = [330. 164.  92. 105.]


In [52]:
# (2) Net, Wealth 계산
Net = np.zeros((10,5))
Wealth = np.zeros((10,5))

for i in range(10):
    for j in range(5):
        Net[i,j] = X[i,j,0] - X[i,j,1] + X[i,j,2]   # Income - Loss + Stock
        Wealth[i,j] = X[i,j,2] + X[i,j,3]           # Stock + House

Y = np.zeros((10,5,2))
Y[:,:,0] = Net
Y[:,:,1] = Wealth

print("Y shape:", Y.shape)   # (10, 5, 2)
print("Y[0,0,:] =", Y[0,0,:])  # 첫 번째 ID, 첫 번째 Year의 [Net, Wealth]


Y shape: (10, 5, 2)
Y[0,0,:] = [258. 197.]


In [53]:
# (3) Export 50x4 table
out = np.zeros((50,4))

k = 0
for i in range(10):
    for j in range(5):
        out[k,0] = data[i*5+j, 0]     # ID
        out[k,1] = data[i*5+j, 1]     # Year
        out[k,2] = Net[i,j]           # Net asset
        out[k,3] = Wealth[i,j]        # Wealth
        k += 1

print("out shape:", out.shape)   # (50, 4)
print(out[:5])                   # 처음 5행 확인

# 파일로 저장 (옵션)
np.savetxt("Hw_1_problem_8_output.csv", out, delimiter=",",
           header="ID,Year,NetAsset,Wealth", comments="", fmt="%.2f")


out shape: (50, 4)
[[  1.   1. 258. 197.]
 [  1.   2. 269. 206.]
 [  1.   3. 280. 215.]
 [  1.   4. 291. 224.]
 [  1.   5. 302. 233.]]


In [54]:
# (4) 행렬 곱 방식 (loop 없이)
W = np.array([
    [1, 0],   # Income
    [-1, 0],  # -Loss
    [1, 1],   # Stock
    [0, 1]    # House
])

Y2 = X @ W   # (10,5,4) @ (4,2) -> (10,5,2)

print("Y2 shape:", Y2.shape)    # (10,5,2)
print("Y2[0,0,:] =", Y2[0,0,:]) # 첫 번째 ID, 첫 번째 Year 결과
print("(2)의 값과 (4)의 값이 같은가?", np.allclose(Y, Y2))



Y2 shape: (10, 5, 2)
Y2[0,0,:] = [258. 197.]
(2)의 값과 (4)의 값이 같은가? True


# Problem 9

## Explanation:
- **(a)** `np.nanmean`, `np.nanstd`를 사용해 NaN을 무시하고 행별 평균과 표준편차를 계산한다.  
  - 예: 두 번째 행 = [3.0, NaN, 2.5, 2.0] → 평균 = (3.0+2.5+2.0)/3 = 2.5,  
    표준편차 = √((0.5² + 0.0² + (−0.5)²)/3) ≈ 0.408.  
- **(b)** 각 행을 표준화하면 평균 0, 표준편차 1이 되며 NaN은 무시된다.  
- **(d)** `σ*M_norm + μ`로 복원하면 원래의 `M` 값이 나온다 (NaN이 아닌 항목에 대해 동일).  
  - Boolean mask를 사용해 NaN을 제외하고 비교한다.  
  - 결과는 `True`가 되어야 한다.  

In [55]:
import numpy as np

# Original matrix with NaN
M = np.array([[500, 520, 540, 560],
              [3.0, np.nan, 2.5, 2.0],
              [50, 52, 55, 57],
              [90, 100, 100, 110]], dtype=float)

print("M:\n", M)

# (a) Mean and std dev per row (ignore NaN)
mu = np.nanmean(M, axis=1)   # shape (4,)
sigma = np.nanstd(M, axis=1, ddof=0)  # population std

print("Row means:", mu)
print("Row std devs:", sigma)


M:
 [[500.  520.  540.  560. ]
 [  3.    nan   2.5   2. ]
 [ 50.   52.   55.   57. ]
 [ 90.  100.  100.  110. ]]
Row means: [530.    2.5  53.5 100. ]
Row std devs: [22.36067977  0.40824829  2.6925824   7.07106781]


In [56]:
# (b) Row-standardized matrix
M_norm = (M - mu[:, None]) / sigma[:, None]
print("M_norm:\n", M_norm)


M_norm:
 [[-1.34164079 -0.4472136   0.4472136   1.34164079]
 [ 1.22474487         nan  0.         -1.22474487]
 [-1.29986737 -0.55708601  0.55708601  1.29986737]
 [-1.41421356  0.          0.          1.41421356]]


In [57]:
# (d) Reconstruction
M_rec = sigma[:, None] * M_norm + mu[:, None]

print("M_rec:\n", M_rec)

# Check equality (ignoring NaN)
mask = ~np.isnan(M)
print("Reconstruction correct?", np.allclose(M_rec[mask], M[mask]))


M_rec:
 [[500.  520.  540.  560. ]
 [  3.    nan   2.5   2. ]
 [ 50.   52.   55.   57. ]
 [ 90.  100.  100.  110. ]]
Reconstruction correct? True


# Problem 10 https://youtu.be/l6r003mzwH0?si=zyMK19aSxTl6xOqg 영상 5:37~6:50

## Explanation:
- (a)에서는 broadcasting으로 \(c\)를 각 행에 더한다.  
- (b)에서는 "상수항(bias)"을 열 벡터로 추가한 뒤, 가중치 행렬에 \(c\)를 붙여서 같은 효과를 얻는다.  
- 두 방식은 수학적으로 동일하며, 실제 계산 결과도 일치한다.

In [58]:
import numpy as np

# Define X, W, c
X = np.array([[160, 55, 170, 65],
              [165, 60, 175, 70],
              [170, 58, 180, 72]])

W = np.array([[0.5, 0.1],
              [0.2, 0.3],
              [0.4, 0.2],
              [0.1, 0.4]])

c = np.array([1.0, 2.0])  # shape (2,)

# (a) Compute Y_hat = XW + c
Y_hat = X @ W + c
print("Y_hat:\n", Y_hat)
print("Y_hat shape:", Y_hat.shape)


Y_hat:
 [[166.5  94.5]
 [172.5  99.5]
 [176.8 101.2]]
Y_hat shape: (3, 2)


In [59]:
# (b) Augmented design trick
ones = np.ones((X.shape[0], 1))   # column of ones, shape (3,1)
X_a = np.hstack((ones, X))        # shape (3,5)

W_a = np.vstack((c.reshape(1, -1), W))  # shape (5,2)

Y_hat_aug = X_a @ W_a
print("Y_hat_aug:\n", Y_hat_aug)

# Verify equality
print("Matches part (a)?", np.allclose(Y_hat, Y_hat_aug))


Y_hat_aug:
 [[166.5  94.5]
 [172.5  99.5]
 [176.8 101.2]]
Matches part (a)? True
